services:
  - type: web
    name: estrada-real-moradores
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/moradores-server.js
    healthCheckPath: /status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_APP_URL
        fromService:
          type: web
          name: estrada-real-moradores
          property: host
  - type: web
    name: estrada-real-portaria
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/portaria-server.js
    healthCheckPath: /status
