services:
  - type: web
    name: estrada-real
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    healthCheckPath: /status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_APP_URL
        fromService:
          type: web
          name: estrada-real
          property: host
